---
kind: pipeline
type: docker
name: run-checks
trigger:
  event:
    - push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: build-test-docker-image
    image: docker:18
    volumes:
      - name: docker
        path: "/var/run/docker.sock"
    commands:
      - docker build -t ${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA} .

  - name: pytest
    image: ${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA}
    environment:
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - source $HOME/.poetry/env
      - $HOME/.poetry/bin/poetry install
      - $HOME/.poetry/bin/poetry run pytest tests/unit

  # Remove the docker image when not master
  - name: delete-docker-image
    image: docker:18
    volumes:
      - name: docker
        path: "/var/run/docker.sock"
    when:
      status: [success, failure]
    commands:
      # Delete the image on a best-effort basis, by always returning 0.
      - docker rmi ${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA} || true
